### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by krizmatic** [Blumlaut/anticheese-anticheat#8]
Better if you can refer to qb-anticheat which is used with QB Framework to add some events

**Comment by Blumlaut** [comment]
What?

**Comment by krizmatic** [comment]
https://github.com/qbcore-framework/qb-anticheat/blob/main/server/main.lua
Refer to the events. It might be helpful. I'm not sure. Ignore if I'm saying something foolish.

**Comment by Blumlaut** [comment]
The problem is that "qb-anticheat" assumes that all ESX events are unregistered, if someone uses ESX this will cause issues immediately, anticheese uses specific patterns to check if an event trigger is malicious in nature or not, this means that some malicious ones go through of course, but ESX users wont have a false positive.
